<?php 

namespace Silverback\WP\Themes\Gazelle;

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(apply_filters('gazelle_bands_fields', array (
	'key' => 'group_5726fa281b6ee',
	'title' => 'Contenuto',
	'fields' => array (
		array (
			'key' => 'field_5726fa357db92',
			'label' => 'Fascie Contenuto',
			'name' => 'content_band',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Aggiungi Fascia',
			'min' => '',
			'max' => '',
			'layouts' => array (
				'image_abstract_button' => array (
					'key' => '5726fa387887d',
					'name' => 'image_abstract_button',
					'label' => 'Immagine abstract e azione',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5726fa8e37d69',
							'label' => 'Titolo',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5726fa9837d6a',
							'label' => 'Sottotitolo',
							'name' => 'subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5726fbe9b2a42',
							'label' => 'Immagine',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5726faab37d6b',
							'label' => 'Testo',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
						),
						array (
							'key' => 'field_5726fac737d6c',
							'label' => 'Link Pulsante',
							'name' => 'button_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5726fade37d6d',
							'label' => 'Testo Pulsante',
							'name' => 'button_label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_576a81bce2c52',
							'label' => 'Full Width',
							'name' => 'full_width',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Full Width',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),

				'map_abstract' => array (
					'key' => '5729bac4a8c1d',
					'name' => 'map_abstract',
					'label' => 'Mappa e testo',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5729bac4a8c1e',
							'label' => 'Titolo',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5729bac4a8c1f',
							'label' => 'Sottotitolo',
							'name' => 'subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5729bae4a8c24',
							'label' => 'Posizione',
							'name' => 'mappa',
							'type' => 'google_map',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'center_lat' => '',
							'center_lng' => '',
							'zoom' => '',
							'height' => '',
						),
						array (
							'key' => 'field_5729bac4a8c21',
							'label' => 'Testo',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'editor_html' => array (
					'key' => '5729bf83d3c0f',
					'name' => 'editor_html',
					'label' => 'Campo HTML',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5729bf9ad3c11',
							'label' => 'Modulo di contatto',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'title_text' => array (
					'key' => '5729f6ff60512',
					'name' => 'title_text',
					'label' => 'Titolo Testo',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5729f71360513',
							'label' => 'Titolo',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5729f72060514',
							'label' => 'Contenuto',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'image_only'=>array (
					'key' => '5729c003d3c12',
					'name' => 'image_only',
					'label' => 'Immagine',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5729c011d3c13',
							'label' => 'Immagine',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'galleria_e_testo'=>array (
					'key' => '5744104e5f4f8',
					'name' => 'galleria_e_testo',
					'label' => 'Galleria e Testo',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5744105b5f4f9',
							'label' => 'Titolo',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5729bac428c1f',
							'label' => 'Sottotitolo',
							'name' => 'subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),						
						array (
							'key' => 'field_574410695f4fa',
							'label' => 'Contenuto',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_574410815f4fb',
							'label' => 'Galleria',
							'name' => 'gallery',
							'type' => 'gallery',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => 2,
							'max' => '',
							'preview_size' => 'band',
							'insert' => 'append',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5826fac737d6c',
							'label' => 'Link Pulsante',
							'name' => 'button_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5826fade37d6d',
							'label' => 'Testo Pulsante',
							'name' => 'button_label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),						
					),
					'min' => '',
					'max' => '',
				),
				'feedback'=>array (
					'key' => '576cdd0e0d661',
					'name' => 'feedback',
					'label' => 'Feedback',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_576cdd27b439d',
							'label' => 'Titolo',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_576cdd74b439f',
							'label' => 'Sottotitolo',
							'name' => 'subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_576cdd83b43a0',
							'label' => 'Feedback',
							'name' => 'feedback',
							'type' => 'repeater',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Aggiungi Riga',
							'sub_fields' => array (
								array (
									'key' => 'field_576cf7d4b43a1',
									'label' => 'Testo',
									'name' => 'testo',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'new_lines' => '',
									'maxlength' => '',
									'placeholder' => '',
									'readonly' => 0,
									'disabled' => 0,
									'rows' => '',
								),
								array (
									'key' => 'field_576cfd5db43a2',
									'label' => 'Autore',
									'name' => 'author',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
				),
				'logos' => array (
					'key' => '576d001746fc8',
					'name' => 'logos',
					'label' => 'Loghi',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_576d001746fc9',
							'label' => 'Titolo',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_576d001746fca',
							'label' => 'Sottotitolo',
							'name' => 'subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_576d001746fcb',
							'label' => 'Loghi',
							'name' => 'logos',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_576d001746fcc',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Aggiungi Riga',
							'sub_fields' => array (
								array (
									'key' => 'field_576d001746fcc',
									'label' => 'Target Url',
									'name' => 'target_url',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_576d001746fcd',
									'label' => 'Immagine Logo',
									'name' => 'logo',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					), 
				), //new templates here
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
)));

if (apply_filters('gazelle_use_subtitles', true)){

	acf_add_local_field_group(array (
		'key' => 'group_571ddd0ca27dd',
		'title' => 'Subtitles',
		'fields' => array (
			array (
				'key' => 'field_571ddd2237991',
				'label' => 'Sottotitolo',
				'name' => 'subtitle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
}

endif;